language: node_js
node_js:
 - "stable"
cache:
 directories:
 - node_modules
script:
 - yarn run build
 - cypress install
 - yarn start & wait-on http://localhost:3001
 - yarn cypress run
 - yarn add surge
deploy:
  provider: surge
  project: ./build/
  domain: giveit.surge.sh
  skip_cleanup: true
  on:
    branch: master
