sudo: false
language: node_js
cache:
  yarn: true
 directories:
 - node_modules
install:
before_script:
  -yarn
script:
  - yarn cypress:open
deploy:
 provider: pages
 skip_cleanup: true
 github_token: ec58741fc9b5bbc9354ef7a712a4929f5b17d4b2
 local_dir: build
 on:
   branch: master
