language: node_js
node_js:
 - "stable"
cache:
 directories:
 - node_modules
script:
 - yarn
 - yarn test
 - yarn run build
deploy:
 provider: pages
 skip_cleanup: true
 github_token: ec58741fc9b5bbc9354ef7a712a4929f5b17d4b2
 local_dir: build
 on:
   branch: master
