describe('Index', function() {
  it('Should Render', function() {
    cy.visit('/')
    cy.contains('app')
    cy.get('#title').type('title')
    cy.get('body').type('body')
    cy.get('#location').type('location')
    cy.get('#start_date').type('start_date')
    cy.get('#end_date').type('end_date')
    cy.contains("submit").click()
  })
  it('should create data object', function() {
    cy.visit('/')
    cy.get('#title')
    .type('Help')
      .should('have.value', 'Help')
    cy.get('#body')
    .type('Need help')
      .should('have.value', 'Need help')
    cy.get('#location')
    .type('Here')
      .should('have.value', 'Here')
    cy.get('#start_date')
    .type('June')
      .should('have.value', 'June')
    cy.get('#end_date')
    .type('July')
      .should('have.value', 'July')
  })
})
